title: Test Camille – Evaboot
description: Blog de test pour présentation à Robin (Evaboot)

author:
  name: Camille
  email: camille@evaboot.com

theme: jekyll-theme-minimal
markdown: kramdown
show_downloads: false
